# Generated by Django 6.0.3 on 2026-03-21 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weapon_type', models.CharField(choices=[('primary', 'Primary'), ('special', 'Special'), ('heavy', 'Heavy')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='Draft', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('patch', 'Patch Notes'), ('event', 'Event'), ('announcement', 'Announcement'), ('update', 'Update'), ('weekly', 'Weekly Reset')], max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('isGameBreaking', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relatedContent', models.ManyToManyField(blank=True, to='core.news')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='Draft', max_length=20)),
                ('build_class', models.CharField(choices=[('titan', 'Titan'), ('hunter', 'Hunter'), ('warlock', 'Warlock')], max_length=20)),
                ('subclass', models.CharField(choices=[('void', 'Void'), ('solar', 'Solar'), ('arc', 'Arc'), ('stasis', 'Stasis'), ('strand', 'Strand'), ('prismatic', 'Prismatic')], max_length=20)),
                ('build_type', models.CharField(choices=[('pve', 'PvE'), ('pvp', 'PvP'), ('endgame', 'Endgame'), ('raid', 'Raid')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('armorMods', models.JSONField(blank=True, null=True)),
                ('statsPriority', models.JSONField(blank=True, null=True)),
                ('expansion', models.CharField(max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_builds', to=settings.AUTH_USER_MODEL)),
                ('exotics', models.ManyToManyField(blank=True, to='core.exotic')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
                ('weapons', models.ManyToManyField(blank=True, to='core.weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
